core_app/urls.py
from django.views.generic.base import RedirectView
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.Index.as_view(), name='index'),
    url(r'^disabled-account/(?P<user_id>.+)/', views.DisabledAccount.as_view(), name='disabled-account'),
    url(r'^switch-organization/(?P<organization_id>.+)/', views.SwitchOrganization.as_view(), name='switch-organization'),
    url(r'^update-user-information/', views.UpdateUserInformation.as_view(), name='update-user-information'),
    url(r'^create-organization/(?P<user_id>.+)/', views.CreateOrganization.as_view(), name='create-organization'),
    url(r'^seen-event/(?P<event_id>.+)/', views.SeenEvent.as_view(), name='seen-event'),

    url(r'^join-organization/(?P<organization_id>.+)/(?P<token>.+)/', views.JoinOrganization.as_view(), name='join-organization'),
    url(r'^signup-from-invite/(?P<organization_id>.+)/(?P<token>.+)/', views.SignupFromInvite.as_view(), name='signup-from-invite'),
    url(r'^update-organization/(?P<organization_id>.+)/', views.UpdateOrganization.as_view(), name='update-organization'),
    url(r'^delete-organization/(?P<organization_id>.+)/', views.DeleteOrganization.as_view(), name='delete-organization'),
    url(r'^list-users/(?P<organization_id>.+)', views.ListUsers.as_view(), name='list-users'),
    url(r'^manage-user-tags/(?P<user_id>.+)', views.ManageUserTags.as_view(), name='manage-user-tags'),
    url(r'^manage-organization-admins/', views.ManageOrganizationAdmins.as_view(), name='manage-organization-admins'),
    url(r'^bind-organization-admin/(?P<organization_id>.+)/(?P<user_id>.+)/', views.BindOrganizationAdmin.as_view(), name='bind-organization-admin'),
    url(r'^unbind-organization-admin/(?P<organization_id>.+)/(?P<user_id>.+)/', views.UnbindOrganizationAdmin.as_view(), name='unbind-organization-admin'),

    url(r'^cancel-invite/(?P<invite_id>.+)', views.CancelInvite.as_view(), name='cancel-invite'),
    url(r'^list-events/', views.ListEvents.as_view(), name='list-events'),
    url(r'^list-invites/', views.ListInvites.as_view(), name='list-invites'),
    url(r'^list-logs/', views.ListLogs.as_view(), name='list-logs'),
    url(r'^all-seen/', views.AllSeen.as_view(), name='all-seen'),
    url(r'^delete-all-clipboard/', views.DeleteAllClipboard.as_view(), name='delete-all-clipboard'),

    url(r'^list-tags/', views.ListTags.as_view(), name='list-tags'),
    url(r'^bind-user-tag/(?P<user_id>.+)/(?P<tag_id>.+)/', views.BindUserTag.as_view(), name='bind-user-tag'),
    url(r'^unbind-user-tag/(?P<user_id>.+)/(?P<tag_id>.+)/', views.UnbindUserTag.as_view(), name='unbind-user-tag'),
    url(r'^create-tag/', views.CreateTag.as_view(), name='create-tag'),
    url(r'^delete-tag/(?P<tag_id>.+)/', views.DeleteTag.as_view(), name='delete-tag'),
    url(r'^invite-organization-user/(?P<organization_id>.+)/', views.InviteOrganizationUser.as_view(), name='invite-organization-user'),
    url(r'^list-clipboard/', views.ListClipboard.as_view(), name='list-clipboard'),
    url(r'^confirm-clipboard-deletion/', views.ConfirmClipboardDeletion.as_view(), name='confirm-clipboard-deletion'),
    url(r'^update-password/', views.UpdatePassword.as_view(), name='update-password'),
    url(r'^disabled-account/$', views.DisabledAccount.as_view(), name='disabled-account'),
    url(r'^remove-organization-user/(?P<user_id>.+)', views.RemoveOrganizationUser.as_view(), name='remove-organization-user'),
    url(r'^resend-invite/(?P<invite_id>.+)', views.ResendInvite.as_view(), name='resend-invite'),

]

opus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
# from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='site_app:index')),
     url(r'^core_app/', include('core_app.urls', namespace='core_app')), 
     url(r'^timeline_app/', include('timeline_app.urls', namespace='timeline_app')), 
     url(r'^comment_app/', include('comment_app.urls', namespace='comment_app')), 
     url(r'^site_app/', include('site_app.urls', namespace='site_app')), 
     url(r'^post_app/', include('post_app.urls', namespace='post_app')), 
     url(r'^timeline_app/', include('timeline_app.urls', namespace='timeline_app')),
     url(r'^paybills/', include('paybills.urls', namespace='paybills')), 
     url(r'^jsim/', include('jsim.urls', namespace='jsim')), 

]


# handler500 = 'core_app.views.default_error'

post_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^post/(?P<post_id>.+)/', views.Post.as_view(), name='post'),
    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),
    url(r'^alert-post-workers/(?P<post_id>.+)/', views.AlertPostWorkers.as_view(), name='alert-post-workers'),

    url(r'^done/(?P<post_id>.+)/', views.Done.as_view(), name='done'),
    url(r'^undo/(?P<post_id>.+)/', views.Undo.as_view(), name='undo'),

    url(r'^create-post/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.CreatePost.as_view(), name='create-post'),
    url(r'^create-post/(?P<ancestor_id>.+)/', views.CreatePost.as_view(), name='create-post'),
    url(r'^update-post/(?P<post_id>.+)/', views.UpdatePost.as_view(), name='update-post'),
    url(r'^attach-file/(?P<post_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),

    url(r'^post-worker-information/(?P<peer_id>.+)/(?P<post_id>.+)/', views.PostWorkerInformation.as_view(), name='post-worker-information'),
    url(r'^post-tag-information/(?P<tag_id>.+)/(?P<post_id>.+)/', views.PostTagInformation.as_view(), name='post-tag-information'),

    url(r'^manage-post-workers/(?P<post_id>.+)/', views.ManagePostWorkers.as_view(), name='manage-post-workers'),
    url(r'^assign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.AssignPostUser.as_view(), name='assign-post-user'),
    url(r'^unassign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.UnassignPostUser.as_view(), name='unassign-post-user'),
    url(r'^setup-post-filter/(?P<timeline_id>.+)', views.SetupPostFilter.as_view(), name='setup-post-filter'),
    url(r'^cut-post/(?P<post_id>.+)/', views.CutPost.as_view(), name='cut-post'),
    url(r'^copy-post/(?P<post_id>.+)/', views.CopyPost.as_view(), name='copy-post'),
    url(r'^manage-post-tags/(?P<post_id>.+)/', views.ManagePostTags.as_view(), name='manage-post-tags'),
    url(r'^bind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.BindPostTag.as_view(), name='bind-post-tag'),
    url(r'^unbind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.UnbindPostTag.as_view(), name='unbind-post-tag'),
    url(r'^cancel-post-creation/(?P<post_id>.+)/', views.CancelPostCreation.as_view(), name='cancel-post-creation'),
    url(r'^request-post-attention/(?P<peer_id>.+)/(?P<post_id>.+)', views.RequestPostAttention.as_view(), name='request-post-attention'),
    url(r'^confirm-post-deletion/(?P<post_id>.+)/', views.ConfirmPostDeletion.as_view(), name='confirm-post-deletion'),
    url(r'^create-fork-/(?P<ancestor_id>.+)/(?P<post_id>.+)/(?P<fork_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    url(r'^create-fork/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    url(r'^select-fork-timeline/(?P<post_id>.+)/', views.SelectForkTimeline.as_view(), name='select-fork-timeline'),
    url(r'^undo-clipboard/(?P<post_id>.+)/', views.UndoClipboard.as_view(), name='undo-clipboard'),
    url(r'^list-all-tasks/', views.ListAllTasks.as_view(), name='list-all-tasks'),
    url(r'^find/', views.Find.as_view(), name='find'),

]

timeline_app/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    url(r'^list-posts/(?P<timeline_id>.+)/', views.ListPosts.as_view(), name='list-posts'),
    url(r'^create-timeline/(?P<organization_id>.+)', views.CreateTimeline.as_view(), name='create-timeline'),
    url(r'^update-timeline/(?P<timeline_id>.+)/', views.UpdateTimeline.as_view(), name='update-timeline'),
    url(r'^delete-timeline/(?P<timeline_id>.+)/', views.DeleteTimeline.as_view(), name='delete-timeline'),
    url(r'^setup-timeline-filter/(?P<organization_id>.+)', views.SetupTimelineFilter.as_view(), name='setup-timeline-filter'),
    url(r'^paste-posts/(?P<timeline_id>.+)/', views.PastePosts.as_view(), name='paste-posts'),
    url(r'^list-timelines/', views.ListTimelines.as_view(), name='list-timelines'),
    url(r'^manage-user-timelines/(?P<user_id>.+)/', views.ManageUserTimelines.as_view(), name='manage-user-timelines'),
    url(r'^manage-timeline-users/(?P<timeline_id>.+)/', views.ManageTimelineUsers.as_view(), name='manage-timeline-users'),
    url(r'^bind-timeline-user/(?P<timeline_id>.+)/(?P<user_id>.+)/', views.BindTimelineUser.as_view(), name='bind-timeline-user'),
    url(r'^unbind-timeline-user/(?P<timeline_id>.+)/(?P<user_id>.+)/', views.UnbindTimelineUser.as_view(), name='unbind-timeline-user'),
    url(r'^timeline-link/(?P<timeline_id>.+)/', views.TimelineLink.as_view(), name='timeline-link'),

]

core_app/forms.py
from django.utils.translation import ugettext_lazy as _
from timeline_app.forms import ConfirmTimelineDeletionForm
from slock.forms import SetPasswordForm
from sqlike.forms import SqLikeForm
from django import forms
from . import models
import datetime


class OrganizationForm(forms.Form):
    name = forms.CharField()

class EventSearchForm(forms.Form):
    pattern = forms.CharField()
    seen = forms.BooleanField(required=False)

class EventFilterForm(forms.Form):
    val0  = datetime.date.today()-datetime.timedelta(days=3)
    start = forms.DateField(initial = val0, widget=forms.SelectDateWidget())

    val1 = datetime.date.today()+datetime.timedelta(days=1)
    end  = forms.DateField(initial = val1, widget=forms.SelectDateWidget())

class TagSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False, 
    help_text='Example:deve + heroes')

class OrganizationInviteForm(forms.Form):
    email = forms.EmailField(help_text="Insert user E-mail.")

class UserForm(forms.ModelForm):
    class Meta:
        model  = models.User
        fields = ('name', 'avatar', 'email')

class UserFilterForm(SqLikeForm, forms.ModelForm):
    class Meta:
        model  = models.UserFilter
        exclude = ('user', 'organization')

class TagForm(forms.ModelForm):
    class Meta:
        model  = models.Tag
        exclude = ('organization', )

class UpdateOrganizationForm(forms.ModelForm):
    class Meta:
        model = models.Organization
        fields = ( 'name', )

class ConfirmOrganizationDeletionForm(ConfirmTimelineDeletionForm):
    name = forms.CharField(required=True,
    help_text='Type the organization name to confirm!')

class RemoveUserForm(forms.Form):
    reason = forms.CharField(required=False, 
    help_text='Thank you for your participation!')

class UserSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False,
    help_text='tag:developer + tag:python')

class SignupForm(SetPasswordForm):
    class Meta:
        model   = models.User
        exclude = ('organizations', 'default', 'service', 
        'expiration', 'max_users', 'paid')

core_app/templates/core_app/confirm-clipboard-deletion.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>

<h5>
<span class="glyphicon glyphicon-remove text-danger"></span>

Delete all clipboard cards/posts?
</h5>

</div>


<div class="modal-body">
<p class="text-danger"> The data will be no longer available, are you sure? </p>
</div>

<div class="modal-footer">

<button  type="button"  data-show="{% url 'core_app:delete-all-clipboard'  %}"
class="btn btn-danger s-modal"> {% trans "Delete" %} </button>

<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

</div>

core_app/templates/core_app/create-organization.html
{% load bootstrap3 %}

{% load i18n %}

<div class="modal-header">
<button type="button"  class="close" data-dismiss="modal">&times;</button>

{% block title %}
<h4>
<span class="glyphicon glyphicon-flag"></span>
Organization </h4>
{% endblock %}

</div>

<div class="modal-body">
{% block body %}

{% endblock %}

<form id="form-organization-data" enctype="multipart/form-data">
{% csrf_token %}

{% block formfields %}
{% bootstrap_field form.name  size='md' %}
{% endblock %}

{% bootstrap_form_errors form type='non_fields' %}
</form>

</div>

<div class="modal-footer">
{% block buttons %}

<button  type="button" data-form="#form-organization-data" 
data-callback="window.location='{% url 'core_app:index' %}';" 
data-shell-error="#smallModalContent" 
data-show="{% url 'core_app:create-organization' user.id %}"
class="btn btn-default e-post">  {% trans "Create" %} </button>
{% endblock %}

</div>

core_app/templates/core_app/create-tag.html
{% load bootstrap3 %}

{% load i18n %}

<div class="modal-header">
<button type="button"  class="close" data-dismiss="modal">&times;</button>
Create Tag
</div>

<div class="modal-body">
<form id="form-tag-data" enctype="multipart/form-data">
{% csrf_token %}

{% bootstrap_field form.name  size='md' %}
{% bootstrap_field form.description  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}
</form>

</div>

<div class="modal-footer">
{% block buttons %}
<button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>

<button  type="button" data-form="#form-tag-data"  data-show="{% url 'core_app:create-tag' %}" 
class="btn btn-default m-post">  {% trans "Create" %} </button>
{% endblock %}

</div>

core_app/templates/core_app/default-error.html
<p> Some error occured, you may no longer have access to this content. 
Send us an e-mail case it persists.
</p>

core_app/templates/core_app/e-bind-user-tag.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a>has tagged 

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.peer.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>

{{event.peer.name}} </a>

with  {{event.tag.name}}  

on {{event.created}}

{% endblock %}

core_app/templates/core_app/e-create-tag.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a>has created tag 

{{event.tag.name}} : {{event.tag.description}}

on {{event.created}}

{% endblock %}

core_app/templates/core_app/e-invite-user.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">
<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a>
has invited {{event.peer.email}} to join

{{event.organization.name}}  

on {{event.created}}

{% endblock %}

core_app/templates/core_app/index.html
<!DOCTYPE html>
{% load i18n %}
{% load jsim %}

<html lang="en">
<head>
<title>Splittask</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="/static/input-extensions.js"> </script>

<link rel="stylesheet" href="/static/opus-main.css">
<link rel="stylesheet" href="/static/pygments.css">

{% block initializer %}
<script>
$(document).ready(function() {
    $('#main-view').load("{% url 'timeline_app:list-timelines' %}");
});

$(function () {
    $('[data-toggle="popover"]').popover()
})

// $(document).ready(function(){
// $('body').tooltip({
    // selector: '[data-toggle="tooltip"]'
// });
// });
</script>
{% endblock %}

{{user.ws_connection | safe}}

<script>
$(document).on('ws-bell', function alertSound(e, sender) {
    var audio = new Audio('/static/event-alert.mp3');
    audio.play();
});

$(document).on('ws-sound', function alertSound(e) {
    var audio = new Audio('/static/event-alert.mp3');
    audio.play();
    $('a.eventsButton').addClass('new-events');
});

$(document).on('ws-alert-event', function alertEvent(e) {
    $('a.eventsButton').addClass('new-events');
});

</script>

</head>

<body>
{% jsim %}

<br>
<div class="clearfix"></div>

<div class="container-fluid">
<a class="e-get" data-show="{% url 'timeline_app:list-timelines' %}" 
data-shell="#main-view"  "
href="#"><span class="glyphicon glyphicon-home"></span>  <b> Home </b></a>

<a class="e-get eventsButton text-success" data-show="{% url 'core_app:list-events' %}" 
data-shell="#smallModalContent"  data-callback="$('#modal').modal('show');$('.eventsButton').removeClass('new-events')"
href="#"><span class="glyphicon glyphicon-bell"></span>  <b> Events </b></a>

<a class="b-modal text-warning"  href="#" data-show="{% url 'post_app:list-all-tasks' %}">
<span class="glyphicon glyphicon-tasks"></span> <b> Tasks </b>
</a>

<a class="b-modal text-info" href="#" data-show="{% url 'post_app:find' %}" >
<span class="glyphicon glyphicon-search"></span> <b> Find </b> </a>

<div id="main-view" > </div>

</div>

</body>

</html>

core_app/templates/core_app/manage-organization-admins.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4>
<span class="glyphicon glyphicon-search"></span>
Available {{organization.name|truncatechars:60}}'s Admins 
<span class="badge">{{count}}/{{total}}</span>
</h4>
</div>

<div class="modal-body">
<div class="pre-scrollable">
<table class="table table-condensed table-bordered">

{% for ind in included %}
<tr id="user-choice-{{ind.id}}" style="font-size:80%">
<td style="width:70px;height:80">
<img style="margin:auto" class="img-responsive" src="{{ind.avatar.url}}" />
</td>

<td> 
<span class="glyphicon glyphicon-user"></span> {{ind.name}}  

<p> {{ind.email}}  </p>

<a class="e-get" style="color:red"
data-callback="$('#user-choice-{{ind.id}}').remove();"
data-show="{% url 'core_app:unbind-organization-admin' organization.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> Remove</a>  

</td>
</tr>
{% endfor %}

{% for ind in excluded %}
<tr id="user-choice-{{ind.id}}" style="font-size:80%">
<td style="width:70px;height:80">
     <img style="margin:auto" class="img-responsive" src="{{ind.avatar.url}}" />
</td>
<td> 
<span class="glyphicon glyphicon-user"></span> {{ind.name}}  

<p> {{ind.email}}  </p>

<a class="e-get"
data-callback="$('#user-choice-{{ind.id}}').remove();"
data-show="{% url 'core_app:bind-organization-admin' organization.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> Bind </a> 

</td>
{% endfor %}

</table>
</div>

<br>

<form id="userSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">

<button  type="button" data-form="#userSearchForm" 
data-shell="#smallModalContent" id="userSearchFormSubmit"
data-shell-error="#smallModalContent" data-show="{% url 'core_app:manage-organization-admins'  %}"
class="btn btn-default e-post"> {% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

<script>
$('#userSearchForm').on('submit', (function(e){
    e.preventDefault();
        $('#userSearchFormSubmit').click();

}));
</script>

core_app/templates/core_app/manage-user-tags.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
Available {{user.name}}'s tags </h5>
</div>

<div class="modal-body">

<div class="pre-scrollable">

{% for ind in included %}
<p id="unbind-user-tag-{{ind.id}}" > <a class="e-get" style="color:red"
data-callback="$('#unbind-user-tag-{{ind.id}}').remove();"
data-show="{% url 'core_app:unbind-user-tag' user.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> </a>  
<b> {{ind.name}} </b>
{{ind.description}} 
</p>
{% endfor %}

{% for ind in excluded %}
<p id="bind-user-tag-{{ind.id}}">

<a class="e-get"
data-callback="$('#bind-user-tag-{{ind.id}}').remove();"
data-show="{% url 'core_app:bind-user-tag' user.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> </a>  
<b>{{ind.name}} </b>

{{ind.description}} 
</p>
{% endfor %}

</div>

<br> 

<form id="tagSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">
<button  type="button" data-show="{% url 'core_app:list-users' me.default.id  %}"
class="btn btn-default s-modal"> {% trans "Back" %} </button>

<button  type="button" data-form="#tagSearchForm" 
data-show="{% url 'core_app:manage-user-tags' user.id  %}" 
class="btn btn-default m-post"> {% trans "Search" %} </button>

<button type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

core_app/templates/core_app/signup-from-invite.html
{% load bootstrap3 %}
{% load i18n %}

<html lang="en">
<head>
<meta charset="utf-8" />
<title>Opus</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="/static/jquery-ui.js"> </script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="/static/input-extensions.js"> </script>
<script src="/static/e-get.js"> </script>
<script src="/static/e-post.js"> </script>

<link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/static/icons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/icons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/static/icons/manifest.json">
<link rel="mask-icon" href="/static/icons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/static/icons/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Opus">
<meta name="application-name" content="arcamens">
<meta name="msapplication-config" content="/static/icons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

</head>

<body>


<div class="container">
<div class="jumbotron">
<h1 >Opus <small> (Sign up) </small></h1> 

<h3> Invited to join {{organization.name}} </h3>

<form id="form-user-data" method="post" enctype="multipart/form-data" action="{% url 'core_app:signup-from-invite' organization.id token %}">
{% csrf_token %}

{% bootstrap_field form.name  size='md' %}
{% bootstrap_field form.email  size='md' %}
{% bootstrap_field form.password  size='md' %}
{% bootstrap_field form.retype  size='md' %}
{% bootstrap_field form.avatar  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}

{% buttons submit='Sign up' layout='inline' %}{% endbuttons %}
</div>

</form>
</div>
</body>

core_app/templates/core_app/update-password.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-remove"></span> Delete organization 

{{organization.name|truncatechars:60}}?
</div>

<div class="modal-body">
<p class="text-warning"> Type your old password and the new one!</p>

<form id="passwordForm" enctype="multipart/form-data">
{% csrf_token %}

{% bootstrap_field form.old  size='md' %}
{% bootstrap_field form.password  size='md' %}
{% bootstrap_field form.retype  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}
</form>

<div class="modal-footer">
<button type="button" class="btn btn-default" 
data-dismiss="modal">Cancel</button>

<button  id="createCard" type="button" data-form="#passwordForm" 
data-show="{% url 'core_app:update-password' %}"
class="btn btn-warning m-post"> 
     {% trans "Update" %}
</button>