opus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
# from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='site_app:index')),
     url(r'^core_app/', include('core_app.urls', namespace='core_app')), 
     url(r'^timeline_app/', include('timeline_app.urls', namespace='timeline_app')), 
     url(r'^comment_app/', include('comment_app.urls', namespace='comment_app')), 
     url(r'^site_app/', include('site_app.urls', namespace='site_app')), 
     url(r'^post_app/', include('post_app.urls', namespace='post_app')), 
     url(r'^timeline_app/', include('timeline_app.urls', namespace='timeline_app')),
     url(r'^paybills/', include('paybills.urls', namespace='paybills')), 
     url(r'^jsim/', include('jsim.urls', namespace='jsim')), 

]


# handler500 = 'core_app.views.default_error'

post_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^post/(?P<post_id>.+)/', views.Post.as_view(), name='post'),
    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),
    url(r'^alert-post-workers/(?P<post_id>.+)/', views.AlertPostWorkers.as_view(), name='alert-post-workers'),

    url(r'^done/(?P<post_id>.+)/', views.Done.as_view(), name='done'),
    url(r'^undo/(?P<post_id>.+)/', views.Undo.as_view(), name='undo'),

    url(r'^create-post/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.CreatePost.as_view(), name='create-post'),
    url(r'^create-post/(?P<ancestor_id>.+)/', views.CreatePost.as_view(), name='create-post'),
    url(r'^update-post/(?P<post_id>.+)/', views.UpdatePost.as_view(), name='update-post'),
    url(r'^attach-file/(?P<post_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),

    url(r'^post-worker-information/(?P<peer_id>.+)/(?P<post_id>.+)/', views.PostWorkerInformation.as_view(), name='post-worker-information'),
    url(r'^post-tag-information/(?P<tag_id>.+)/(?P<post_id>.+)/', views.PostTagInformation.as_view(), name='post-tag-information'),

    url(r'^manage-post-workers/(?P<post_id>.+)/', views.ManagePostWorkers.as_view(), name='manage-post-workers'),
    url(r'^assign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.AssignPostUser.as_view(), name='assign-post-user'),
    url(r'^unassign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.UnassignPostUser.as_view(), name='unassign-post-user'),
    url(r'^setup-post-filter/(?P<timeline_id>.+)', views.SetupPostFilter.as_view(), name='setup-post-filter'),
    url(r'^cut-post/(?P<post_id>.+)/', views.CutPost.as_view(), name='cut-post'),
    url(r'^copy-post/(?P<post_id>.+)/', views.CopyPost.as_view(), name='copy-post'),
    url(r'^manage-post-tags/(?P<post_id>.+)/', views.ManagePostTags.as_view(), name='manage-post-tags'),
    url(r'^bind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.BindPostTag.as_view(), name='bind-post-tag'),
    url(r'^unbind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.UnbindPostTag.as_view(), name='unbind-post-tag'),
    url(r'^cancel-post-creation/(?P<post_id>.+)/', views.CancelPostCreation.as_view(), name='cancel-post-creation'),
    url(r'^request-post-attention/(?P<peer_id>.+)/(?P<post_id>.+)', views.RequestPostAttention.as_view(), name='request-post-attention'),
    url(r'^confirm-post-deletion/(?P<post_id>.+)/', views.ConfirmPostDeletion.as_view(), name='confirm-post-deletion'),
    url(r'^create-fork-/(?P<ancestor_id>.+)/(?P<post_id>.+)/(?P<fork_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    url(r'^create-fork/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    url(r'^select-fork-timeline/(?P<post_id>.+)/', views.SelectForkTimeline.as_view(), name='select-fork-timeline'),
    url(r'^undo-clipboard/(?P<post_id>.+)/', views.UndoClipboard.as_view(), name='undo-clipboard'),
    url(r'^list-all-tasks/', views.ListAllTasks.as_view(), name='list-all-tasks'),
    url(r'^find/', views.Find.as_view(), name='find'),

]

timeline_app/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    url(r'^list-posts/(?P<timeline_id>.+)/', views.ListPosts.as_view(), name='list-posts'),
    url(r'^create-timeline/(?P<organization_id>.+)', views.CreateTimeline.as_view(), name='create-timeline'),
    url(r'^update-timeline/(?P<timeline_id>.+)/', views.UpdateTimeline.as_view(), name='update-timeline'),
    url(r'^delete-timeline/(?P<timeline_id>.+)/', views.DeleteTimeline.as_view(), name='delete-timeline'),
    url(r'^setup-timeline-filter/(?P<organization_id>.+)', views.SetupTimelineFilter.as_view(), name='setup-timeline-filter'),
    url(r'^paste-posts/(?P<timeline_id>.+)/', views.PastePosts.as_view(), name='paste-posts'),
    url(r'^list-timelines/', views.ListTimelines.as_view(), name='list-timelines'),
    url(r'^manage-user-timelines/(?P<user_id>.+)/', views.ManageUserTimelines.as_view(), name='manage-user-timelines'),
    url(r'^manage-timeline-users/(?P<timeline_id>.+)/', views.ManageTimelineUsers.as_view(), name='manage-timeline-users'),
    url(r'^bind-timeline-user/(?P<timeline_id>.+)/(?P<user_id>.+)/', views.BindTimelineUser.as_view(), name='bind-timeline-user'),
    url(r'^unbind-timeline-user/(?P<timeline_id>.+)/(?P<user_id>.+)/', views.UnbindTimelineUser.as_view(), name='unbind-timeline-user'),
    url(r'^timeline-link/(?P<timeline_id>.+)/', views.TimelineLink.as_view(), name='timeline-link'),

]

post_app/forms.py
from django import forms
from sqlike.forms import SqLikeForm
from . import models

class PostForm(forms.ModelForm):
    class Meta:
        model  = models.Post
        exclude = ('user', 'ancestor', 
            'html', 'parent')

class PostFileWrapperForm(forms.ModelForm):
    class Meta:
        model  = models.PostFileWrapper
        exclude = ('post', )

class PostFilterForm(SqLikeForm, forms.ModelForm):
    class Meta:
        model  = models.PostFilter
        exclude = ('user', 'timeline')

class GlobalPostFilterForm(SqLikeForm, forms.ModelForm):
    class Meta:
        model  = models.GlobalPostFilter
        exclude = ('user', 'organization')

class GlobalTaskFilterForm(SqLikeForm, forms.ModelForm):
    class Meta:
        model  = models.GlobalTaskFilter
        exclude = ('user', 'organization')

        widgets = {
            'options': forms.RadioSelect,
        }

class UserSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False,
    help_text='Example: tag:engineer + tag:rocket')

class TagSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False)

class PostAttentionForm(forms.Form):
    message = forms.CharField(
    required=False, widget=forms.Textarea,
    help_text='(Optional) Be in the meeting 20 min earlier.')

class AlertPostWorkersForm(forms.Form):
    message = forms.CharField(
    required=False, widget=forms.Textarea,
    help_text='Please, take a look at this asap!')

class TimelineSearchform(forms.Form):
    pattern = forms.CharField(required=False, 
    help_text='Ex: Todo')

post_app/views.py
from post_app.models import EUnbindTagPost, ECreatePost, EUpdatePost, \
PostFileWrapper, EDeletePost, EAssignPost, EBindTagPost, EUnassignPost, \
PostFilter, GlobalPostFilter, ECutPost, EArchivePost, ECopyPost, GlobalTaskFilter, EUnarchivePost
from django.db.models import Q, F, Exists, OuterRef, Count, Sum
from core_app.models import Clipboard, Tag, User
from django.shortcuts import render, redirect
from core_app.views import GuardianView
from django.core.urlresolvers import reverse
from django.views.generic import View
from django.core.mail import send_mail
from django.http import HttpResponse
from jsim.jscroll import JScroll
from timeline_app.models import Timeline, EPastePost
from django.db.models.functions import Concat
from functools import reduce
from django.conf import settings
from . import forms
from . import models
from re import split
import operator
import json

class Post(GuardianView):
    """
    """

    def get(self, request, post_id):
        post = models.Post.objects.get(id=post_id)

        if not post.ancestor:
            return HttpResponse("This post is on clipboard!\
                It can't be accessed now.", status=403)

        user = User.objects.get(id=self.user_id)
        
        # Check if logged user has access to the post.
        has_access = user.timelines.filter(id=post.ancestor_id).exists()
        has_access = has_access or post.workers.filter(id=user.id).exists()

        if not has_access:
            return HttpResponse("You can't access this post!", status=403)

        return render(request, 'post_app/post.html', {'post':post,  })

class PostLink(GuardianView):
    """
    """

    def get(self, request, post_id):
        post = models.Post.objects.get(id=post_id)

        if not post.ancestor:
            return HttpResponse("This post is on clipboard!\
                It can't be accessed now.", status=403)

        user = User.objects.get(id=self.user_id)

        # Check if logged user has access to the post.
        has_access = user.timelines.filter(id=post.ancestor_id).exists()
        has_access = has_access or post.workers.filter(id=user.id).exists()

        if not has_access:
            return HttpResponse("You can't access this post!", status=403)

        attachments = post.postfilewrapper_set.all()
        workers = post.workers.all()

        organizations = user.organizations.exclude(id=user.default.id)

        queues = list(map(lambda ind: 'timeline%s' % ind, 
        user.timelines.values_list('id')))

        return render(request, 'post_app/post-link.html', 
        {'post':post, 'attachments': attachments, 
        'tags': post.tags.all(), 'workers': workers,
        'user': user, 'default': user.default, 'organization': user.default,
        'organizations': organizations, 'queues': json.dumps(queues),
         'settings': settings})

class CreatePost(GuardianView):
    """
    """

    def get(self, request, ancestor_id, post_id=None):
        ancestor   = Timeline.objects.get(id=ancestor_id)
        user       = User.objects.get(id=self.user_id)
        post       = models.Post.objects.create(user=user, ancestor=ancestor)
        form       = forms.PostForm(instance=post)
        post.label = 'Draft.'
        post.save()
        return render(request, 'post_app/create-post.html', 
        {'form':form, 'post': post, 'ancestor':ancestor})

    def post(self, request, ancestor_id, post_id):
        post     = models.Post.objects.get(id=post_id)
        ancestor = Timeline.objects.get(id=ancestor_id)

        form = forms.PostForm(request.POST, request.FILES, instance=post)
        if not form.is_valid():
            return render(request, 'post_app/create-post.html',
                        {'form': form, 'post':post, 
                                'ancestor': ancestor}, status=400)

        post.save()
        user  = User.objects.get(id=self.user_id)
        event = ECreatePost.objects.create(organization=user.default,
        timeline=ancestor, post=post, user=user)

        users = ancestor.users.all()
        event.dispatch(*users)

        user.ws_sound(post.ancestor)

        return redirect('timeline_app:list-posts', 
        timeline_id=ancestor_id)

class UpdatePost(GuardianView):
    def get(self, request, post_id):
        post = models.Post.objects.get(id=post_id)
        return render(request, 'post_app/update-post.html',
        {'post': post, 'form': forms.PostForm(instance=post)})

    def post(self, request, post_id):
        record  = models.Post.objects.get(id=post_id)
        form    = forms.PostForm(request.POST, request.FILES, instance=record)

        if not form.is_valid():
            return render(request, 'post_app/update-post.html',
                   {'post': record, 'form': form}, status=400)
        record.save()

        user  = User.objects.get(id=self.user_id)
        event = EUpdatePost.objects.create(organization=user.default,
        timeline=record.ancestor, post=record, user=user)

        event.dispatch(*record.ancestor.users.all())

        # Notify workers of the event, in case the post
        # is on a timeline whose worker is not on.
        event.dispatch(*record.workers.all())

        user.ws_sound(record.ancestor)

        return redirect('post_app:post', 
        post_id=record.id)


class AttachFile(GuardianView):
    """
    """

    def get(self, request, post_id):
        post = models.Post.objects.get(id=post_id)
        attachments = post.postfilewrapper_set.all()
        form = forms.PostFileWrapperForm()
        return render(request, 'post_app/attach-file.html', 
        {'post':post, 'form': form, 'attachments': attachments})

    def post(self, request, post_id):
        post = models.Post.objects.get(id=post_id)
        attachments = post.postfilewrapper_set.all()
        form = forms.PostFileWrapperForm(request.POST, request.FILES)

        if not form.is_valid():
            return render(request, 'post_app/attach-file.html', 
                {'post':post, 'form': form, 'attachments': attachments})
        record = form.save(commit = False)
        record.post = post
        form.save()
        return self.get(request, post_id)

class DetachFile(GuardianView):
    """
    """

    def get(self, request, filewrapper_id):
        filewrapper = PostFileWrapper.objects.get(id=filewrapper_id)
        filewrapper.delete()
        attachments = filewrapper.post.postfilewrapper_set.all()

        form = forms.PostFileWrapperForm()
        return render(request, 'post_app/attach-file.html', 
        {'post':filewrapper.post, 'form': form, 'attachments': attachments})

class DeletePost(GuardianView):
    def get(self, request, post_id):
        post = models.Post.objects.get(id = post_id)
        # post.delete()

        user  = User.objects.get(id=self.user_id)

        event = EDeletePost.objects.create(organization=user.default,
        timeline=post.ancestor, post_label=post.label, user=user)
        users = post.ancestor.users.all()
        event.dispatch(*users)

        ancestor = post.ancestor
        post.delete()

        user.ws_sound(post.ancestor)

        return redirect('timeline_app:list-posts', 
        timeline_id=ancestor.id)

class PostWorkerInformation(GuardianView):
    def get(self, request, peer_id, post_id):
        event = EAssignPost.objects.filter(post__id=post_id,
        peer__id=peer_id).last()

        active_tasks = event.peer.assignments.filter(done=False)
        done_tasks = event.peer.assignments.filter(done=True)
        active_tasks = active_tasks.count()
        done_tasks   = done_tasks.count()

        return render(request, 
        'post_app/post-worker-information.html',  
        {'peer': event.peer, 'active_tasks': active_tasks, 
         'post': event.post,  'done_tasks': done_tasks,
        'created': event.created, 'user':event.user})

class PostTagInformation(GuardianView):
    def get(self, request, tag_id, post_id):
        event = EBindTagPost.objects.filter(post__id=post_id,
        tag__id=tag_id).last()

        return render(request, 'post_app/post-tag-information.html', 
        {'user': event.user, 'created': event.created, 'tag':event.tag})

class UnassignPostUser(GuardianView):
    def get(self, request, post_id, user_id):
        user = User.objects.get(id=user_id)
        post = models.Post.objects.get(id=post_id)
        me   = User.objects.get(id=self.user_id)

        me.ws_sound(post.ancestor)

        event = EUnassignPost.objects.create(
        organization=me.default, ancestor=post.ancestor, 
        post=post, user=me, peer=user)

        event.dispatch(*post.ancestor.users.all())
        
        # As posts can be assigned to users off the timeline.
        # We make sure them get the evvent.
        event.dispatch(*post.workers.all())
        event.save()

        post.workers.remove(user)
        post.save()

        return HttpResponse(status=200)

class AssignPostUser(GuardianView):
    def get(self, request, post_id, user_id):
        user = User.objects.get(id=user_id)
        post = models.Post.objects.get(id=post_id)
        me = User.objects.get(id=self.user_id)

        post.workers.add(user)
        post.save()

        event = EAssignPost.objects.create(
        organization=me.default, ancestor=post.ancestor, 
        post=post, user=me, peer=user)

        event.dispatch(*post.ancestor.users.all())
        event.dispatch(*post.workers.all())
        event.save()

        me.ws_sound(post.ancestor)

        return HttpResponse(status=200)

class ManagePostWorkers(GuardianView):
    def get(self, request, post_id):
        me = User.objects.get(id=self.user_id)
        post = models.Post.objects.get(id=post_id)

        included = post.workers.all()
        excluded = me.default.users.exclude(assignments=post)
        total    = included.count() + excluded.count()

        return render(request, 'post_app/manage-post-workers.html', 
        {'included': included, 'excluded': excluded, 'post': post,

post_app/templates/post_app/confirm-post-deletion.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-remove"></span> Delete post {{post.label|truncatechars:60}}?
</div>

<div class="modal-body">
<p class="text-danger"> The content will no longer be avaiable!</p>

{% if post.children.exists %}
<p class="text-warning"> It is gonna delete all post's forks, are you sure? </p>
{% endif %}
</div>


<div class="modal-footer">
<button type="button" class="btn btn-default" 
data-dismiss="modal">Cancel</button>

<button  id="createpost" type="button" 
data-shell="#main-view" data-callback="$('#modal').modal('toggle');" 
data-shell-error="#smallModalContent" data-show="{% url 'post_app:delete-post' post.id %}"
class="btn btn-danger e-get"> 
     {% trans "Delete" %}
</button>


<script>

post_app/templates/post_app/e-bind-tag-post.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span> {{user.name}} 
{{event.user.name}} </a> has tagged post

<a class="e-get"
data-callback="$('#modal').modal('toggle');" 
data-shell="#main-view"
data-show="{% url 'post_app:post' event.post.id %}" href="{{event.post.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.post.label|truncatechars:60}} </a>  

with
<span class="glyphicon glyphicon-tag"></span> {{event.tag.name}} on timeline 

<a class="e-get"
data-callback="$('#modal').modal('toggle');" 

data-shell="#main-view"
data-show="{% url 'timeline_app:list-posts' event.ancestor.id %}" href="{{event.ancestor.get_link_url}}"> 
<span class="glyphicon glyphicon-share"></span> {{event.ancestor.name}} 
</a>

on {{event.created}}

{% endblock %}

post_app/templates/post_app/e-copy-post.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}
Post
<a class="e-get"
data-shell="#main-view"
data-callback="$('#modal').modal('toggle');" 
data-show="{% url 'post_app:post' event.post.id %}"
href="{{event.post.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.post.label|truncatechars:60}} </a>

was copied from timeline

<a class="e-get"
data-callback="$('#modal').modal('toggle');" 
data-shell="#main-view"
data-show="{% url 'timeline_app:list-posts' event.timeline.id %}" href="{{event.timeline.get_link_url}}"> 
<span class="glyphicon glyphicon-share"></span> {{event.timeline.name}} </a>  by 

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>

{{event.user}} </a> on {{event.created}}

{% endblock %}

post_app/templates/post_app/e-create-post.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}
Post
<a class="e-get"
data-callback="$('#modal').modal('toggle');" 
data-shell="#main-view"
data-show="{% url 'post_app:post' event.post.id %}"
href="{{event.post.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{event.post.label|truncatechars:60}} </a> created on timeline

<a class="e-get"
data-callback="$('#modal').modal('toggle');" 

data-shell="#main-view"
data-show="{% url 'timeline_app:list-posts' event.timeline.id %}" href="{{event.timeline.get_link_url}}"> 
<span class="glyphicon glyphicon-share"></span> {{event.timeline.name}} </a>  by 

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> on {{event.created}}

{% endblock %}

post_app/templates/post_app/manage-post-tags.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
Available {{post.label|truncatechars:40}} post's tags </h5>
</div>

<div class="modal-body">

<div class="pre-scrollable">

{% for ind in included %}
<p id="unbind-post-tag-{{ind.id}}" > <a class="e-get" style="color:red"
data-callback="$('#unbind-post-tag-{{ind.id}}').remove();"
data-show="{% url 'post_app:unbind-post-tag' post.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> </a>  <b> {{ind.name}} </b>
 {{ind.description}} 
</p>
{% endfor %}

{% for ind in excluded %}
<p id="bind-post-tag-{{ind.id}}">
<a class="e-get"
data-callback="$('#bind-post-tag-{{ind.id}}').remove();"
data-show="{% url 'post_app:bind-post-tag' post.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> </a>  <b> {{ind.name}} </b>
 {{ind.description}} 
</p>
{% endfor %}

</div>

<br> 

<form id="tagSearchForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">
<script>
$('#modal').one('hidden.bs.modal', function () {
    $('#post-{{post.id}}').load('{% url 'post_app:post' post.id  %}');
})
</script>

<button  type="button" data-form="#tagSearchForm" data-show="{% url 'post_app:manage-post-tags' post.id  %}"
class="btn btn-default m-post"> {% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

post_app/templates/post_app/manage-post-workers.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% load avatar %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h5>
<span class="glyphicon glyphicon-search"></span>
Available <span class="glyphicon glyphicon-file"></span> {{post.label|truncatechars:"60"}} post's workers 
<span class="badge">{{count}}/{{total}}</span>
</h5>
</div>

<div class="modal-body">
<div class="pre-scrollable">
<table class="table table-condensed table-bordered">

{% for ind in included %}
<tr id="user-choice-{{ind.id}}" style="font-size:80%">
<td style="width:70px;height:80">
<img style="margin:auto" class="img-responsive" src="{% avatar ind.avatar %}" />
</td>

<td> 
<span class="glyphicon glyphicon-user"></span> {{ind.name}}  

<p> {{ind.email}}  </p>

<a class="e-get text-danger" 
data-callback="$('#user-choice-{{ind.id}}').remove();"
data-show="{% url 'post_app:unassign-post-user' post.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> Unbind</a>  

</td>
</tr>
{% endfor %}

{% for ind in excluded %}
<tr id="user-choice-{{ind.id}}" style="font-size:80%">
<td style="width:70px;height:80">
     <img style="margin:auto" class="img-responsive" src="{% avatar ind.avatar %}" />
</td>
<td> 
<span class="glyphicon glyphicon-user"></span> {{ind.name}}  

<p> {{ind.email}}  </p>

<a class="e-get" 
data-callback="$('#user-choice-{{ind.id}}').remove();"
data-show="{% url 'post_app:assign-post-user' post.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> bind </a> 

</td>
{% endfor %}

</table>
</div>



<br> 

<form id="assign-post-search-form" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">
<script>
$('#modal').one('hidden.bs.modal', function () {
    $('#post-{{post.id}}').load('{% url 'post_app:post' post.id  %}');
})
</script>

<button  type="button" data-form="#assign-post-search-form" data-show="{% url 'post_app:manage-post-workers' post.id  %}"
class="btn btn-default m-post"> {% trans "Filter" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

post_app/templates/post_app/request-post-attention.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>

<h5> 
<span class="glyphicon glyphicon-envelope"></span>
Call {{peer.name}} attention on post 
<span class="glyphicon glyphicon-file"></span>

{{post.label|truncatechars:40}}</h5>
</div>

<div class="modal-body">
<form id="requestpostAttentionForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.message  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>


<div class="modal-footer">
<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Cancel" %}
</button>

<button  type="button" data-form="#requestpostAttentionForm" 
data-show="{% url 'post_app:request-post-attention' peer.id post.id  %}"
class="btn btn-default m-post"> {% trans "Send e-mail" %} </button>

</div>