opus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
# from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='site_app:index')),
     url(r'^core_app/', include('core_app.urls', namespace='core_app')), 
     url(r'^timeline_app/', include('timeline_app.urls', namespace='timeline_app')), 
     url(r'^comment_app/', include('comment_app.urls', namespace='comment_app')), 
     url(r'^site_app/', include('site_app.urls', namespace='site_app')), 
     url(r'^post_app/', include('post_app.urls', namespace='post_app')), 
     url(r'^timeline_app/', include('timeline_app.urls', namespace='timeline_app')),
     url(r'^paybills/', include('paybills.urls', namespace='paybills')), 
     url(r'^jsim/', include('jsim.urls', namespace='jsim')), 

]


# handler500 = 'core_app.views.default_error'

post_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^post/(?P<post_id>.+)/', views.Post.as_view(), name='post'),
    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),
    url(r'^alert-post-workers/(?P<post_id>.+)/', views.AlertPostWorkers.as_view(), name='alert-post-workers'),

    url(r'^done/(?P<post_id>.+)/', views.Done.as_view(), name='done'),
    url(r'^undo/(?P<post_id>.+)/', views.Undo.as_view(), name='undo'),

    url(r'^create-post/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.CreatePost.as_view(), name='create-post'),
    url(r'^create-post/(?P<ancestor_id>.+)/', views.CreatePost.as_view(), name='create-post'),
    url(r'^update-post/(?P<post_id>.+)/', views.UpdatePost.as_view(), name='update-post'),
    url(r'^attach-file/(?P<post_id>.+)/', views.AttachFile.as_view(), name='attach-file'),
    url(r'^detach-file/(?P<filewrapper_id>.+)/', views.DetachFile.as_view(), name='detach-file'),
    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^delete-post/(?P<post_id>.+)/', views.DeletePost.as_view(), name='delete-post'),
    url(r'^post-link/(?P<post_id>.+)/', views.PostLink.as_view(), name='post-link'),

    url(r'^post-worker-information/(?P<peer_id>.+)/(?P<post_id>.+)/', views.PostWorkerInformation.as_view(), name='post-worker-information'),
    url(r'^post-tag-information/(?P<tag_id>.+)/(?P<post_id>.+)/', views.PostTagInformation.as_view(), name='post-tag-information'),

    url(r'^manage-post-workers/(?P<post_id>.+)/', views.ManagePostWorkers.as_view(), name='manage-post-workers'),
    url(r'^assign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.AssignPostUser.as_view(), name='assign-post-user'),
    url(r'^unassign-post-user/(?P<post_id>.+)/(?P<user_id>.+)', views.UnassignPostUser.as_view(), name='unassign-post-user'),
    url(r'^setup-post-filter/(?P<timeline_id>.+)', views.SetupPostFilter.as_view(), name='setup-post-filter'),
    url(r'^cut-post/(?P<post_id>.+)/', views.CutPost.as_view(), name='cut-post'),
    url(r'^copy-post/(?P<post_id>.+)/', views.CopyPost.as_view(), name='copy-post'),
    url(r'^manage-post-tags/(?P<post_id>.+)/', views.ManagePostTags.as_view(), name='manage-post-tags'),
    url(r'^bind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.BindPostTag.as_view(), name='bind-post-tag'),
    url(r'^unbind-post-tag/(?P<post_id>.+)/(?P<tag_id>.+)', views.UnbindPostTag.as_view(), name='unbind-post-tag'),
    url(r'^cancel-post-creation/(?P<post_id>.+)/', views.CancelPostCreation.as_view(), name='cancel-post-creation'),
    url(r'^request-post-attention/(?P<peer_id>.+)/(?P<post_id>.+)', views.RequestPostAttention.as_view(), name='request-post-attention'),
    url(r'^confirm-post-deletion/(?P<post_id>.+)/', views.ConfirmPostDeletion.as_view(), name='confirm-post-deletion'),
    url(r'^create-fork-/(?P<ancestor_id>.+)/(?P<post_id>.+)/(?P<fork_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    url(r'^create-fork/(?P<ancestor_id>.+)/(?P<post_id>.+)/', views.CreateFork.as_view(), name='create-fork'),
    url(r'^select-fork-timeline/(?P<post_id>.+)/', views.SelectForkTimeline.as_view(), name='select-fork-timeline'),
    url(r'^undo-clipboard/(?P<post_id>.+)/', views.UndoClipboard.as_view(), name='undo-clipboard'),
    url(r'^list-all-tasks/', views.ListAllTasks.as_view(), name='list-all-tasks'),
    url(r'^find/', views.Find.as_view(), name='find'),

]

timeline_app/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    url(r'^list-posts/(?P<timeline_id>.+)/', views.ListPosts.as_view(), name='list-posts'),
    url(r'^create-timeline/(?P<organization_id>.+)', views.CreateTimeline.as_view(), name='create-timeline'),
    url(r'^update-timeline/(?P<timeline_id>.+)/', views.UpdateTimeline.as_view(), name='update-timeline'),
    url(r'^delete-timeline/(?P<timeline_id>.+)/', views.DeleteTimeline.as_view(), name='delete-timeline'),
    url(r'^setup-timeline-filter/(?P<organization_id>.+)', views.SetupTimelineFilter.as_view(), name='setup-timeline-filter'),
    url(r'^paste-posts/(?P<timeline_id>.+)/', views.PastePosts.as_view(), name='paste-posts'),
    url(r'^list-timelines/', views.ListTimelines.as_view(), name='list-timelines'),
    url(r'^manage-user-timelines/(?P<user_id>.+)/', views.ManageUserTimelines.as_view(), name='manage-user-timelines'),
    url(r'^manage-timeline-users/(?P<timeline_id>.+)/', views.ManageTimelineUsers.as_view(), name='manage-timeline-users'),
    url(r'^bind-timeline-user/(?P<timeline_id>.+)/(?P<user_id>.+)/', views.BindTimelineUser.as_view(), name='bind-timeline-user'),
    url(r'^unbind-timeline-user/(?P<timeline_id>.+)/(?P<user_id>.+)/', views.UnbindTimelineUser.as_view(), name='unbind-timeline-user'),
    url(r'^timeline-link/(?P<timeline_id>.+)/', views.TimelineLink.as_view(), name='timeline-link'),

]

timeline_app/forms.py
from django.utils.translation import ugettext_lazy as _
from sqlike.forms import SqLikeForm
from django import forms
from . import models

class TimelineForm(forms.ModelForm):
    class Meta:
        model  = models.Timeline
        exclude = ('owner', 'organization', 'users')

class FilterForm(forms.Form):
    pattern = forms.CharField()

class FindUserForm(forms.Form):
    pattern = forms.CharField()

class TimelineFilterForm(forms.ModelForm):
    class Meta:
        model  = models.TimelineFilter
        exclude = ('user', 'organization')

class BindTimelinesForm(forms.Form):
    name = forms.CharField(required=False)

# class ListUsersSearchForm(forms.Form):
    # pattern = forms.CharField(required=False)

class FindEventForm(forms.Form):
    pattern = forms.CharField()
    seen = forms.BooleanField(required=False)

class UserSearchForm(SqLikeForm, forms.Form):
    pattern = forms.CharField(required=False)

class ConfirmTimelineDeletionForm(forms.Form):
    name = forms.CharField(required=True,
    help_text='Type the timeline name to confirm!')

    def __init__(self, *args, confirm_token='', **kwargs):
        self.confirm_token = confirm_token

        super(ConfirmTimelineDeletionForm, 
            self).__init__(*args, **kwargs)

    def clean(self):
        super(ConfirmTimelineDeletionForm, self).clean()
        name   = self.cleaned_data.get('name')

        if name != self.confirm_token:
            raise forms.ValidationError(
                "The name doesn't match!")

timeline_app/views.py
from timeline_app.models import Timeline, ECreateTimeline, EDeleteTimeline, \
EUnbindTimelineUser, EUpdateTimeline, EPastePost, TimelineFilter, EBindTimelineUser
from post_app.models import Post, PostFilter
from core_app.models import Organization, User, Clipboard
from core_app.views import GuardianView
from django.shortcuts import render, redirect
from jsim.jscroll import JScroll
from django.http import HttpResponse
from django.views.generic import View
from django.conf import settings
from django.db.models import Q
import post_app.models
import operator
from . import forms
from . import models
import json
# Create your views here.

class ListPosts(GuardianView):
    """
    """

    def get(self, request, timeline_id):
        timeline  = Timeline.objects.get(id=timeline_id)
        user      = User.objects.get(id=self.user_id)

        filter, _ = PostFilter.objects.get_or_create(
        user=user, timeline=timeline)

        posts      = timeline.posts.all()
        total      = posts.count()

        posts = filter.collect(posts)
        count = posts.count()

        posts = posts.order_by('-created')
        posts = JScroll(user.id,'timeline_app/list-posts-scroll.html', posts)

        return render(request, 'timeline_app/list-posts.html', 
        {'timeline':timeline, 'count': count, 'total': total, 
        'posts':posts.as_window(), 'filter': filter})

class CreateTimeline(GuardianView):
    """
    """

    def get(self, request, organization_id):
        form = forms.TimelineForm()
        return render(request, 'timeline_app/create-timeline.html', 
        {'form':form, 'user_id': self.user_id, 'organization_id':organization_id})

    def post(self, request, organization_id):
        form = forms.TimelineForm(request.POST)

        if not form.is_valid():
            return render(request, 'timeline_app/create-timeline.html',
                        {'form': form, 'user_id':self.user_id, 
                                'organization_id': organization_id}, status=400)

        organization = Organization.objects.get(id=organization_id)
        user         = User.objects.get(id=self.user_id)
        record       = form.save(commit=False)
        record.owner = user
        record.organization  = organization
        form.save()
        record.users.add(user)
        record.save()

        event = ECreateTimeline.objects.create(organization=user.default,
        timeline=record, user=user)

        event.dispatch(user)

        user.ws_subscribe(record)
        user.ws_sound()

        return redirect('timeline_app:list-timelines')

class DeleteTimeline(GuardianView):
    def get(self, request,  timeline_id):
        timeline = Timeline.objects.get(id = timeline_id)
        form = forms.ConfirmTimelineDeletionForm()

        return render(request, 'timeline_app/delete-timeline.html', 
        {'timeline': timeline, 'form': form})

    def post(self, request, timeline_id):
        timeline = Timeline.objects.get(id = timeline_id)

        form = forms.ConfirmTimelineDeletionForm(request.POST, 
        confirm_token=timeline.name)

        if not form.is_valid():
            return render(request, 
                'timeline_app/delete-timeline.html', 
                    {'timeline': timeline, 'form': form}, status=400)

        user     = User.objects.get(id=self.user_id)
        event    = EDeleteTimeline.objects.create(organization=user.default,
        timeline_name=timeline.name, user=user)

        # Tell all the users of the timeline to unsubscribe.
        user.ws_sound(timeline)

        # It should work because the queues are the same.
        # So the sound event would arrive first.
        user.ws_unsubscribe(timeline, target=timeline)

        # should tell users to unsubscribe here.
        # it may hide bugs.
        event.dispatch(*timeline.users.all())
        timeline.delete()

        return redirect('timeline_app:list-timelines')

class UnbindTimelineUser(GuardianView):
    def get(self, request, timeline_id, user_id):
        user = User.objects.get(id=user_id)
        timeline = Timeline.objects.get(id=timeline_id)

        if timeline.owner == user:
            return HttpResponse("You can't remove \
                the timeline owner!", status=403)

        timeline.users.remove(user)
        timeline.save()

        me    = User.objects.get(id=self.user_id)
        event = EUnbindTimelineUser.objects.create(organization=me.default,
        timeline=timeline, user=me, peer=user)

        event.dispatch(*timeline.users.all())

        me.ws_sound(timeline)

        # When user is removed from timline then it
        # gets unsubscribed from the timeline.
        # The logged user is sending the event
        # to the user queue that is going to receive
        # the unsubscribe evvent.
        me.ws_unsubscribe(timeline, target=user)

        # As said before, order of events cant be determined
        # when dispatched towards two queues. It might
        # happen of sound event being dispatched before subscribe event.
        # So, we warrant sound to happen.
        me.ws_sound(user)

        return HttpResponse(status=200)

class UpdateTimeline(GuardianView):
    def get(self, request, timeline_id):
        timeline = Timeline.objects.get(id=timeline_id)
        return render(request, 'timeline_app/update-timeline.html',
        {'timeline': timeline, 'form': forms.TimelineForm(instance=timeline)})

    def post(self, request, timeline_id):
        record  = Timeline.objects.get(id=timeline_id)
        form    = forms.TimelineForm(request.POST, instance=record)

        if not form.is_valid():
            return render(request, 
                'timeline_app/update-timeline.html',
                     {'timeline': record, 'form': form})
        form.save()

        user  = User.objects.get(id=self.user_id)
        event = EUpdateTimeline.objects.create(
        organization=user.default, timeline=record, user=user)

        event.dispatch(*record.users.all())

        user.ws_sound(record)

        return redirect('timeline_app:list-posts', 
        timeline_id=record.id)

class PastePosts(GuardianView):
    def get(self, request, timeline_id):
        timeline = Timeline.objects.get(id=timeline_id)
        user     = User.objects.get(id=self.user_id)
        users    = timeline.users.all()

        clipboard, _ = Clipboard.objects.get_or_create(
        user=user, organization=user.default)

        posts = clipboard.posts.all()
        if not posts.exists():
            return HttpResponse("There is no post on \
                the clipboard.", status=403)

        posts.update(ancestor=timeline)

        event = EPastePost(
        organization=user.default, timeline=timeline, user=user)
        event.save(hcache=False)
        event.posts.add(*posts)
        event.dispatch(*users)
        event.save()

        user.ws_sound(timeline)
        clipboard.posts.clear()

        return redirect('timeline_app:list-posts', 
        timeline_id=timeline.id)

class SetupTimelineFilter(GuardianView):
    def get(self, request, organization_id):
        filter = TimelineFilter.objects.get(
        user__id=self.user_id, organization__id=organization_id)
        organization = Organization.objects.get(id=organization_id)

        return render(request, 'timeline_app/setup-timeline-filter.html', 
        {'form': forms.TimelineFilterForm(instance=filter), 
        'organization': organization})

    def post(self, request, organization_id):
        record = TimelineFilter.objects.get(
        organization__id=organization_id, user__id=self.user_id)

        form   = forms.TimelineFilterForm(request.POST, instance=record)
        organization = Organization.objects.get(id=organization_id)

        if not form.is_valid():
            return render(request, 'timeline_app/setup-timeline-filter.html',
                   {'timeline': record, 'form': form, 
                        'organization': organization}, status=400)
        form.save()
        return redirect('timeline_app:list-timelines')

class ListEvents(GuardianView):
    """
    """

    def get(self, request):
        user   = User.objects.get(id=self.user_id)
        events = user.events.filter(organization=user.default).order_by('-created')

        # Missing dynamic filter.
        total = user.events.filter(organization=user.default).order_by('-created')

        form = forms.FindEventForm()
        return render(request, 'timeline_app/list-events.html',
        {'user': user, 'events': events, 'form': form, 
        'total': total, 'organization': user.default})

class ListTimelines(GuardianView):
    """
    """

    def get(self, request):
        user      = User.objects.get(id=self.user_id)
        filter, _ = TimelineFilter.objects.get_or_create(
        user=user, organization=user.default)

        total = user.timelines.filter(organization=user.default)
        children = total.filter(Q(name__icontains=filter.pattern) | \
        Q(description__icontains=filter.pattern) if filter.status \
        else Q(organization=user.default))

        organizations = user.organizations.exclude(id=user.default.id)

        return render(request, 'timeline_app/list-timelines.html', 
        {'user': user, 'children': children, 'total': total, 
        'organizations': organizations, 'organization':user.default, 
        'filter': filter})

class BindTimelineUser(GuardianView):
    def get(self, request, timeline_id, user_id):
        user = User.objects.get(id=user_id)
        timeline = Timeline.objects.get(id=timeline_id)

        timeline.users.add(user)
        timeline.save()

        me    = User.objects.get(id=self.user_id)
        event = EBindTimelineUser.objects.create(organization=me.default,
        timeline=timeline, user=me, peer=user)

        event.dispatch(*timeline.users.all())

        me.ws_sound(timeline)
        me.ws_subscribe(timeline, target=user)

timeline_app/templates/timeline_app/delete-timeline.html
{% load bootstrap3 %}
{% load i18n %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<span class="glyphicon glyphicon-remove"></span> Delete timeline 

{{timeline.name|truncatechars:60}}?
</div>

<div class="modal-body">
<p class="text-danger"> The content will no longer be avaiable!</p>

<form id="confirmTimelineDeletionForm" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.name  size='md' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>

<div class="modal-footer">
<button type="button" class="btn btn-default" 
data-dismiss="modal">Cancel</button>

<button  id="createCard" type="button" data-form="#confirmTimelineDeletionForm"
data-shell="#main-view" data-callback="$('#modal').modal('toggle');" 
data-shell-error="#smallModalContent" data-show="{% url 'timeline_app:delete-timeline' timeline.id %}"
class="btn btn-danger e-post"> 
     {% trans "Delete" %}
</button>

timeline_app/templates/timeline_app/e-bind-timeline-user.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.peer.email}}"  data-content="{{event.user.name}}">
<span class="glyphicon glyphicon-user"></span>

{{event.peer.name}} </a> binded to

<a class="e-get"
data-callback="$('#modal').modal('toggle');" 
data-shell="#main-view"
data-show="{% url 'timeline_app:list-posts' event.timeline.id %}" href="{{event.timeline.get_link_url}}"> 
<span class="glyphicon glyphicon-share"></span> {{event.timeline.name}} </a>  by 

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> on {{event.created}}

{% endblock %}

timeline_app/templates/timeline_app/e-create-timeline.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}
Timeline
<a class="e-get"
data-callback="$('#modal').modal('toggle');" 
data-shell="#main-view"
data-show="{% url 'timeline_app:list-posts' event.timeline.id %}" href="{{event.timeline.get_link_url}}"> 
<span class="glyphicon glyphicon-share"></span>
{{event.timeline.name}} </a> created on 

<span class="glyphicon glyphicon-flag"></span>

{{event.organization.name}} by 

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> on {{event.created}}

{% endblock %}

timeline_app/templates/timeline_app/e-delete-timeline.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}

Timeline 
<span style="color:red"> 

<span class="glyphicon glyphicon-share"></span>
{{event.timeline_name}} </span> deleted by 

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>

{{event.user}} </a> on {{event.created}}

{% endblock %}

timeline_app/templates/timeline_app/e-paste-post.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}
<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">

<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> has pasted

{% for ind in event.posts.all %}
<a class="e-get"
data-callback="$('#modal').modal('toggle');" 
data-shell="#main-view"
data-show="{% url 'post_app:post' ind.id %}"
href="{{ind.get_link_url}}"> 
<span class="glyphicon glyphicon-file"></span>
{{ind.label|truncatechars:60}} {% if ind.task %} <b> *Task* </b> {% endif %}</a> 

{% endfor %}

on timeline 

<a class="e-get"
data-callback="$('#modal').modal('toggle');" 

data-shell="#main-view"
data-show="{% url 'timeline_app:list-posts' event.timeline.id %}" href="{{event.timeline.get_link_url}}"> 
<span class="glyphicon glyphicon-share"></span> {{event.timeline.name}} </a>  by 

 on {{event.created}}

{% endblock %}

timeline_app/templates/timeline_app/e-update-timeline.html
{% extends 'timeline_app/event.html' %}
{% load i18n %}

{% block content %}

Timeline <a class="e-get"
data-shell="#main-view"
data-callback="$('#modal').modal('toggle');" 
data-show="{% url 'timeline_app:list-posts' event.timeline.id %}" href="{{event.timeline.get_link_url}}"> 
<span class="glyphicon glyphicon-share"></span>
{{event.timeline.name}} </a>  updated by 

<a href="#" data-toggle="popover" data-trigger="hover" title="{{event.user.email}}"  data-content="{{event.user.name}}">
<span class="glyphicon glyphicon-user"></span>
{{event.user}} </a> on {{event.created}}

{% endblock %}

timeline_app/templates/timeline_app/list-posts-menu-timeline.html
{% load i18n %}

<ul class="nav nav-pills menu-timeline">

<li class="disabled">
<a  href="#"> <b><span class="glyphicon glyphicon-share"></span>  
{{timeline.name|slice:":20"}}'s Posts: <span class="badge">{{count}}/{{total}}</span></b> </a>
</li>

<li data-toggle="tooltip" title="Up">
<a class="e-get" data-show="{% url 'timeline_app:list-timelines' %}"
data-shell="#main-view" data-show="" href="#">
<span class="glyphicon glyphicon glyphicon-arrow-up clip"></span> Up
</a>
</li>

<li><a class="e-get" data-shell="#smallModalContent" 
data-show="{% url 'timeline_app:update-timeline' timeline.id %}" 
data-toggle="modal" data-target="#modal" 
href="#"> <span class="glyphicon glyphicon-cog"></span> 
Settings</a></li>

<li class="divider"></li>

<li><a class="e-get" 
data-shell="#smallModalContent" data-callback="$('#modal').modal('show');"
data-show="{% url 'timeline_app:manage-timeline-users' timeline.id %}" href="#">
<span class="glyphicon glyphicon-user"></span>  {% trans "Members" %}</a></li>

<li class="divider"></li>

<li> <a class="e-get" data-shell="#smallModalContent" data-show="{% url 'post_app:setup-post-filter' timeline.id %}"
data-callback="$('#modal').modal('show');" href="#">
{% if filter.status %}
<span class="glyphicon glyphicon-filter"></span> 
Filter
{% else %}
<strike> 
<span class="glyphicon glyphicon-filter"></span> 
Filter </strike>

{% endif %}
</a></li>


<li> <a class="e-get" data-shell="#bigModalContent" data-callback="$('#bigModal').modal('show');" 
data-show="{% url 'post_app:create-post' timeline.id %}" href="#">
<span class="glyphicon glyphicon-plus"></span> {% trans "Post" %}</a></li>

<li><a class="e-get" data-shell="#main-view" 
data-show="{% url 'timeline_app:paste-posts' timeline.id %}" href="#">
<span class="glyphicon glyphicon-paste"></span>  {% trans "Paste" %}</a></li>

</ul>

timeline_app/templates/timeline_app/manage-timeline-users.html
{% load bootstrap3 %}
{% load i18n %}
{% load static %}
{% load avatar %}


<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4>
<span class="glyphicon glyphicon-search"></span>
Available {{timeline.name|truncatechars:60}}'s users 
<span class="badge">{{count}}/{{total}}</span>
</h4>
</div>

<div class="modal-body">
<div class="pre-scrollable">
<table class="table table-condensed table-bordered">

{% for ind in included %}
<tr id="user-choice-{{ind.id}}" style="font-size:80%">
<td style="width:70px;height:80">
<img style="margin:auto" class="img-responsive" src="{% avatar ind.avatar %}" />
</td>

<td> 
<span class="glyphicon glyphicon-user"></span> {{ind.name}}  

<p> {{ind.email}}  </p>

<a class="e-get" style="color:red"
data-callback="$('#user-choice-{{ind.id}}').remove();"
data-show="{% url 'timeline_app:unbind-timeline-user' timeline.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-remove"></span> Remove</a>  

</td>
</tr>
{% endfor %}

{% for ind in excluded %}
<tr id="user-choice-{{ind.id}}" style="font-size:80%">
<td style="width:70px;height:80">
     <img style="margin:auto" class="img-responsive" src="{% avatar ind.avatar %}" />
</td>
<td> 
<span class="glyphicon glyphicon-user"></span> {{ind.name}}  

<p> {{ind.email}}  </p>

<a class="e-get"
data-callback="$('#user-choice-{{ind.id}}').remove();"
data-show="{% url 'timeline_app:bind-timeline-user' timeline.id ind.id %}" href="#"> 
<span class="glyphicon glyphicon-plus"></span> Bind </a> 

</td>
{% endfor %}

</table>
</div>

<br>

<form id="bind-timeline-search-form" enctype="multipart/form-data">
{% csrf_token %}
{% bootstrap_field form.pattern  size='md' layout='inline' %}
{% bootstrap_form_errors form type='non_fields' %}
</form>
</div>

<div class="modal-footer">

<button  type="button" data-form="#bind-timeline-search-form" 
data-shell="#smallModalContent" data-shell-error="#smallModalContent" data-show="{% url 'timeline_app:manage-timeline-users' timeline.id  %}"
class="btn btn-default e-post"> {% trans "Search" %} </button>

<button  type="button" data-dismiss="modal" class="btn btn-default"> 
     {% trans "Close" %}
</button>

</div>

timeline_app/templates/timeline_app/update-timeline.html
{% extends "timeline_app/create-timeline.html" %}
{% load i18n %}

{% block title %}
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4 class="modal-title">
<span class="glyphicon glyphicon-cog"></span>
{{timeline.name}}'s settings</h4>
{% endblock %}

{% block buttons %}

<button  type="button"  
data-shell="#smallModalContent"
data-show="{% url 'timeline_app:delete-timeline' timeline.id %}"
class="btn btn-danger e-get"> 
{% trans "Delete" %}
</button>

<button  type="button" data-form="#form-timeline-data" 
data-shell="#main-view" data-show="{% url 'timeline_app:update-timeline' timeline.id %}"
class="btn btn-default m-post-close">  {% trans "Update" %} </button>

{% endblock %}