opus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
# from django.conf.urls import handler404, handler500

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(pattern_name='site_app:index')),
     url(r'^core_app/', include('core_app.urls', namespace='core_app')), 
     url(r'^timeline_app/', include('timeline_app.urls', namespace='timeline_app')), 
     url(r'^comment_app/', include('comment_app.urls', namespace='comment_app')), 
     url(r'^site_app/', include('site_app.urls', namespace='site_app')), 
     url(r'^post_app/', include('post_app.urls', namespace='post_app')), 
     url(r'^timeline_app/', include('timeline_app.urls', namespace='timeline_app')),
     url(r'^paybills/', include('paybills.urls', namespace='paybills')), 
     url(r'^jsim/', include('jsim.urls', namespace='jsim')), 

]


# handler500 = 'core_app.views.default_error'

site_app/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^index/', views.Index.as_view(), name='index'),
    url(r'^logged-out/', views.LoggedOut.as_view(), name='logged-out'),
    url(r'^login/', views.Login.as_view(), name='login'),
    url(r'^logout/', views.Logout.as_view(), name='logout'),
    url(r'^signup/', views.SignUp.as_view(), name='signup'),
    url(r'^upgrade/', views.Upgrade.as_view(), name='upgrade'),
    url(r'^confirm-downgrade-free/', views.ConfirmDowngradeFree.as_view(), name='confirm-downgrade-free'),
    # url(r'^downgrade-free-success/', views.DowngradeFreeSuccess.as_view(), name='downgrade-free-success'),
    url(r'^downgrade-free/', views.DowngradeFree.as_view(), name='downgrade-free'),
    # url(r'^downgrade-free-error/', views.DowngradeFreeError.as_view(), name='downgrade-free-error'),
    url(r'^paypal-manual-payment/', views.PaypalManualPayment.as_view(), name='paypal-manual-payment'),
    url(r'^calculate-period-cost/', views.CalculatePeriodCost.as_view(), name='calculate-period-cost'),
    url(r'^paypal-ipn/', views.PayPalIPN.as_view(), name='paypal-ipn'),
    url(r'^custom-payment/', views.CustomPayment.as_view(), name='custom-payment'),
    url(r'^recover-account/', views.RecoverAccount.as_view(), name='recover-account'),
    url(r'^redefine-password/(?P<user_id>.+)/(?P<token>.+)/', views.RedefinePassword.as_view(), name='redefine-password'),
    url(r'^enable-account/(?P<user_id>.+)/(?P<token>.+)/', views.EnableAccount.as_view(), name='enable-account'),
]

site_app/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings
import random

class RegisterProcessMixin:
    def save(self, *args, **kwargs):
        self.token = 'signup%s' % random.randint(1000, 10000)

        signup_url = reverse('site_app:enable-account', 
        kwargs={'user_id': self.user.id, 'token': self.token})

        self.signup_url = '%s%s' % (settings.LOCAL_ADDR, signup_url)

        send_mail('Confirm your account', '%s' % self.signup_url, 
        'noreply@splittask.net', [self.user.email], fail_silently=False)
        super().save(*args, **kwargs)

class PasswordTicket(models.Model):
    token = models.CharField(null=True,
    blank=False, max_length=256)

    user = models.ForeignKey('core_app.User', null=True, 
    related_name='password_tickets', blank=True)

    # expiration = models.DateTimeField(blank=True, null=True)
    created = models.DateTimeField(auto_now=True, null=True)

class RegisterProcess(RegisterProcessMixin, models.Model):
    # email = models.EmailField(max_length=70, 
    # null=True, blank=False)
    user = models.OneToOneField('core_app.User', null=True, 
    blank=True, related_name='register_process')

    # should have a count to avoid mail spam.
    token = models.CharField(null=True,
    blank=False, max_length=256)

    signup_url = models.CharField(null=True,
    blank=False, max_length=256)

site_app/forms.py
from slock.forms import SetPasswordForm
from django.conf import settings
from django import forms
from captcha.fields import ReCaptchaField
import core_app.models
import datetime

class RecoverAccountForm(forms.Form):
    email = forms.EmailField()

    def clean(self):
        super(RecoverAccountForm, self).clean()
        email = self.cleaned_data.get('email')

        try:
            user = core_app.models.User.objects.get(
                email = email)
        except Exception as e:
            raise forms.ValidationError(
                "This user doesn't exist!")

class SignupForm(SetPasswordForm):
    captcha = ReCaptchaField()

    class Meta:
        model   = core_app.models.User
        exclude = ('organizations', 'default', 'expiration',
        'enabled', 'paid', 'max_users')

class PeriodForm(forms.ModelForm):
    expiration = forms.DateField(widget=forms.SelectDateWidget())

    def __init__(self, *args, max_users=None, expiration=None, **kwargs):
        self.max_users  = max_users
        self.expiration = expiration
        super(PeriodForm, self).__init__(*args, **kwargs)

    class Meta:
        model   = core_app.models.Period
        exclude = ('user', 'price', 'total', 'paid')

    def clean(self):
        super().clean()

        if self.errors:
            return

        max_users = self.cleaned_data.get('max_users')
        if max_users <= settings.FREE_MAX_USERS:
            raise forms.ValidationError("That is a free plan.")
        elif max_users < self.max_users:
            raise forms.ValidationError("Max users can't be \
                smaller than your account members number!")

        expiration = self.cleaned_data.get('expiration')
        if expiration <= datetime.date.today():
            raise forms.ValidationError("That is not a valid date.")
        elif self.expiration and expiration < self.expiration:
            raise forms.ValidationError("Expiration can't be \
                smaller than your current expiration!")
        elif self.expiration and expiration == self.expiration and max_users == self.max_users:
            raise forms.ValidationError("Either increase the number of users \
                or increase expiration date!")

site_app/views.py
from paybills.submitters import ManualForm
from core_app.models import Organization, Period
from slock.views import AuthenticatedView, LogoutView, LoginView
from django.shortcuts import render, redirect
from slock.forms import SetPasswordForm
from site_app.models import PasswordTicket, RegisterProcess
from django.core.mail import send_mail
from django.views.generic import View
from django.http import HttpResponse
from slock.forms import LoginForm
from django.urls import reverse
from django.utils.timezone import now
from django.conf import settings
from core_app.models import User
import paybills.views
from . import forms
import timeline_app
import datetime
import time
import random

class Index(LoginView):
    def get(self, request):
        return render(request, 'site_app/index.html', 
        {'form':LoginForm()})

class LoggedOut(View):
    def get(self, request):
        return render(request, 
        'site_app/logged-out.html', {})

class Login(LoginView):
    """
    """

    def get(self, request):
        return render(request, 'site_app/index.html', 
        {'form':LoginForm()})

    def post(self, request):
        form = LoginForm(request.session, request.POST)

        if not form.is_valid():
            return render(request, 'site_app/index.html',
                        {'form': form})

        return redirect('core_app:index')

class Logout(LogoutView):
    """
    """

class SignUp(LoginView):
    """
    """

    def get(self, request):
        form = forms.SignupForm()
        return render(request, 'site_app/signup.html', 
        {'form': form,})

    def post(self, request):
        """
        This is called after the user has filled the user fields
        and picked up a plan. The plan can be created on the fly
        or just be fixed(in case we decide futurely change how we
        charge on opus). 
        """
        form = forms.SignupForm(request.POST, request.FILES)

        if not form.is_valid():
            return render(request, 'site_app/signup.html', 
                {'form': form}, status=400)

        # Save the user record. The Period model
        # has a field named enabled, it is False for default
        # unless it is a free plan whose record is created by us.
        record         = form.save(commit=False)
        # record.enabled = True

        record.save()
        organization   = Organization.objects.create(name='Main', owner=record)
        record.default = organization
        record.organizations.add(organization)
        record.save()

        process = RegisterProcess.objects.create(user=record)

        return render(request, 
            'site_app/confirm-email.html', {'user': record})

class EnableAccount(View):
    def get(self, request, user_id, token):
        process = RegisterProcess.objects.get(user__id=user_id, token=token)
        process.user.enabled = True
        process.user.save()
        process.delete()

        # When the user login its first plan is free.
        period = Period.objects.create(paid=False, total=0, user=process.user)

        process.user.max_users  = period.max_users
        process.user.expiration = period.expiration
        process.user.paid       = period.paid

        request.session['user_id'] = user_id
        return redirect('core_app:index')

class CustomPayment(AuthenticatedView):
    """
    """

    def get(self, request):
        return render(request, 'site_app/custom-payment.html', {})

class Upgrade(AuthenticatedView):
    def get(self, request):
        me    = User.objects.get(id=self.user_id)
        items = me.items.all().order_by('-created')
        # processes = me.manual_proceses.all().order_by('-created')

        return render(request, 'site_app/upgrade.html', 
        {'items': items, 'me': me, 'CURRENCY_CODE': settings.CURRENCY_CODE})

class ConfirmDowngradeFree(AuthenticatedView):
    def get(self, request):
        me      = User.objects.get(id=self.user_id)
        n_users = me.n_acc_users()

        # if not me.paid:
            # return HttpResponse('Your plan is already free!', status=403)

        return render(request, 'site_app/confirm-downgrade-free.html', 
        {'n_users':n_users, 'me': me, 'settings': settings})

class DowngradeFree(AuthenticatedView):
    def get(self, request):
        me      = User.objects.get(id=self.user_id)
        n_users = me.n_acc_users()

        if n_users > settings.FREE_MAX_USERS:
            return render(request, 'site_app/downgrade-free-max-users-error.html', 
                {'me': me, 'n_users':n_users}, status=403)

        if me.expiration > datetime.date.today():
            return render(request, 'site_app/downgrade-free-expiration-error.html', 
                {'me': me, 'n_users':n_users}, status=403)

        period        = Period.objects.create(paid=False, total=0, user=me)
        me.max_users  = period.max_users
        me.expiration = period.expiration
        me.paid       = period.paid
        me.save()

        return render(request, 'site_app/downgrade-free-success.html', {})

class CalculatePeriodCost(AuthenticatedView):
    def post(self, request):
        me   = User.objects.get(id=self.user_id)
        form = forms.PeriodForm(request.POST, 
            max_users=me.max_users, expiration=me.expiration)

        if not form.is_valid():
            return render(request, 
                'site_app/paypal-manual-payment.html', {'form':form, 
                    'me': me, 'USER_COST':settings.USER_COST, 'CURRENCY_CODE': settings.CURRENCY_CODE}, status=400)

        now  = datetime.date.today()
        init = me.expiration if me.expiration and me.expiration > now else now
        d0   = init - now
        rate = settings.USER_COST/30.0
        cash = rate * d0.days * me.max_users 
        d1   = form.cleaned_data['expiration'] - now
        cost = form.cleaned_data['max_users'] * rate * d1.days - cash
        cost = round(cost, 3)

        return render(request, 'site_app/paypal-manual-payment.html', 
        {'form':form, 'me': me, 'cost': cost, 'USER_COST':settings.USER_COST, 'CURRENCY_CODE': settings.CURRENCY_CODE})

class PaypalManualPayment(AuthenticatedView):
    """
    Users just make use of submmiters to start
    the payment process. It allows a high level of
    flexibility on how to customize the offering of
    products.
    """

    def get(self, request):
        # We should check if user has some payment process going on
        # so we avoid receiving twice.
        me   = User.objects.get(id=self.user_id)
        form = forms.PeriodForm(initial={'max_users': me.max_users,
        'expiration': me.expiration})

        return render(request, 'site_app/paypal-manual-payment.html', 
        {'form':form, 'me': me, 'USER_COST':settings.USER_COST, 'CURRENCY_CODE': settings.CURRENCY_CODE})

    def post(self, request):
        me   = User.objects.get(id=self.user_id)
        form = forms.PeriodForm(request.POST, 
            max_users=me.max_users, expiration=me.expiration)

        # I need to check if the user has decreased the max_users
        # value to a smaller value than its total account users.
        # If so then he has to remove users for decreasing its max_users
        # value.
        if not form.is_valid():
            return render(request, 
                'site_app/paypal-manual-payment.html', {'form':form, 
                    'me': me, 'USER_COST':settings.USER_COST, 'CURRENCY_CODE': settings.CURRENCY_CODE}, status=400)

        record      = form.save(commit=False)
        record.paid = True
        record.user = me

        now  = datetime.date.today()
        init = me.expiration if me.expiration and me.expiration > now else now
        d0   = init - now
        rate = settings.USER_COST/30.0 
        cash = rate * d0.days * me.max_users 
        d1   = form.cleaned_data['expiration'] - now
        cost = form.cleaned_data['max_users'] * rate * d1.days - cash
        cost = round(cost, 3)

        record.total = cost
        record.save()

        # Fields that are related to generating the
        # html form. 
        payload = {
        'item_name': "Splittask Period",
        'currency_code': settings.CURRENCY_CODE,
        'amount': cost,
        'quantity': 1,
        'shopping_url': 'https://staging.splittask.net',
        'return': 'https://staging.splittask.net',
        'cancel_return': 'https://staging.splittask.net',
        # 'image_url': 'http://FIXME.gif',
        'no_shipping': '1'}

        # The product that is being sold is cached.
        # When the manual payment happens then it retrieves
        # the product it was bought and update the user account
        # attributes. These are expiration, max_users.
        manual = ManualForm(me, record, payload)
        return HttpResponse(manual)

class PayPalIPN(paybills.views.PayPalIPN):
    """
    When a payment is made it calls on_success method
    regardless whether it is a subscription or manual.
    """

    def on_success(self, data, user, item):
        """
        Users should override this method to perform
        actions when payments are made.

        Periods that should be enabled for a given
        period of time should increase its service timeout
        value here.

        The timeout procedure for a service should be implemented
        on its own, it shouldnt be implemented in register_app for
        avoiding loss of flexibility.
        """
    
        # If the payment in fact happens then the user
        # acquired the product so we update the user account
        # attributes regarding the product.
        user.enabled    = True
        user.max_users  = item.period.max_users
        user.expiration = item.period.expiration
        user.paid       = item.period.paid

        print('Setting user attributes on PaypalIPN')
        print('User:', user.name)
        print('Max users:', user.max_users)
        print('Expiration:', user.expiration)
        print('Paid:', user.paid)

site_app/templates/site_app/confirm-downgrade-free.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4> <span class="glyphicon glyphicon-heart-empty"></span> Free Plan </h4>
</div>

<div class="modal-body">

<p class="text-warning">
Are you sure you want to downgrade?
</p>

<p> Your actual limits are: <br>
<b> Total Users:  {{n_users}} </b>
<br>
<small class="text-info">  All your organization users summed up. </small>
</p>

<p> 
<b> Max Users: {{me.max_users}} </b>
</br>
<small class="text-info"> The max amount of users all your organizations can have when summed up. </small></p>

<p class="text-danger">
Your account organizations will have at most {{settings.FREE_MAX_USERS}} users when summed up.
</p>
</div>

<div class="modal-footer">
<button  type="button" data-show="{% url 'site_app:upgrade' %}"
class="btn btn-default s-modal"> {% trans "Back" %} </button>

<button  type="button" data-show="{% url 'site_app:downgrade-free' %}" 
class="btn btn-default s-modal"> {% trans "Do it!" %} </button>

</div>

site_app/templates/site_app/confirm-email.html
{% load bootstrap3 %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Splittask</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <div class="jumbotron">
    <h1>Splittask</h1> 

<p>An e-mail was sent to {{user.email}}. Click on the link for confirming your account. </p> 


</div>
</div>


</body>
</html>

site_app/templates/site_app/index.html
<!DOCTYPE html>
{% load bootstrap3 %}
{% load i18n %}
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Splittask</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="/static/jquery-ui.js"> </script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="/static/input-extensions.js"> </script>
<script src="/static/e-get.js"> </script>

<link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/static/icons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/icons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/static/icons/manifest.json">
<link rel="mask-icon" href="/static/icons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/static/icons/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Splittask">
<meta name="application-name" content="Splittask">
<meta name="msapplication-config" content="/static/icons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">

<style>
footer{
   background-color: #424558;
    bottom: 0;
    left: 0;
    right: 0;
    text-align: center;
    color: #CCC;
}

footer p {
    padding: 10.5px;
    margin: 0px;
    line-height: 100%;
}
</style>

</head>
<body>


<nav class="navbar navbar-inverse">
<div class="container-fluid">
<div class="navbar-header">
<a class="navbar-brand" href="#">
<span class="glyphicon glyphicon-share"></span> Splittask </a>
    
</div>

<ul class="nav navbar-nav">
<li><a href="{% url 'site_app:signup' %}" >
<span class="glyphicon glyphicon-user"></span> {% trans "Sign up" %}</a></li>

<li><a href="/static/help/index.html"" target="_blank">
<span class="glyphicon glyphicon-book"></span> {% trans "Help" %}</a></li>

</ul>

<ul class="nav navbar-right">

<form class="navbar-form navbar-left" method="post" action="{% url 'site_app:login' %}">
{% csrf_token %}

{% bootstrap_field form.email layout='inline' %}
{% bootstrap_field form.password layout='inline' %}
{% buttons submit='Sign in' layout='inline' %}{% endbuttons %}

</form>

</ul>

</div>
</nav>

<div class="container">
{% if form.errors %}
<div class="text-right">
<a href="{% url 'site_app:recover-account' %}" >
<span class="glyphicon glyphicon-lock"></span> Lost password?</a>
</div>
{% endif %}

{% bootstrap_form_errors form type='non_fields' %}
</div>
{% include 'site_app/home.html' %}

<footer style="align-center">
<p>© 2018<a style="color:#0a93a6; text-decoration:none;" href="#"> Splittask</a>, All rights reserved 2017-2018.
<br> 
<a href="mailto:contact@Splittask.com">contact@Splittask.net</a>
</p>
</footer>

</body>
</html>

site_app/templates/site_app/paypal-manual-payment.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h3> <span class="glyphicon glyphicon-credit-card"></span>

Paypal <small> Manual Payment </small></h3>

</div>
<div class="modal-body">

<form id="paypalManualPaymentForm" enctype="multipart/form-data">
{% csrf_token %}

{% bootstrap_field form.max_users  size='md' %}
{% bootstrap_field form.expiration  size='md' %}

{% bootstrap_form_errors form type='non_fields' %}

</form>
<p> <b> Total Cost: {{cost}} {{CURRENCY_CODE}}</b> <br>
<small class="text-info"> Cost based on current expiration and max users limit. 

<span class="text-warning"> Cost per user {{USER_COST}} {{CURRENCY_CODE}} per 30 days. </span>
</small></p>

</div>

<div class="modal-footer">

<button  type="button" data-show="{% url 'site_app:upgrade' %}"
class="btn btn-default s-modal"> {% trans "Back" %} </button>

<button  type="button" data-show="{% url 'site_app:calculate-period-cost' %}" data-form="#paypalManualPaymentForm"
class="btn btn-default m-post"> {% trans "Calc/Cost" %} </button>

<button  type="button" data-show="{% url 'site_app:paypal-manual-payment' %}" data-form="#paypalManualPaymentForm"
class="btn btn-default m-post"> {% trans "Purchase" %} </button>

</div>

site_app/templates/site_app/recover-account.html
{% load bootstrap3 %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Splittask</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
  <div class="jumbotron">
    <h1>Splittask</h1> 

<p>Insert your primary or secondary e-mail. We'll send you a link for
redefining a new password. </p> 

<div class="row">
<div class="col-md-5">
<form action="{% url 'site_app:recover-account' %}" method="post">
{% csrf_token %}
{% bootstrap_field form.email  size='md' %}
{% buttons submit='Send' layout='inline' %}{% endbuttons %}

</form>
</div>

</div>

</div>
{% bootstrap_form_errors form type='non_fields' %}

</div>


</body>
</html>

site_app/templates/site_app/redefine-password.html
{% load bootstrap3 %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Opus</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/paho-mqtt/1.0.1/mqttws31.js" type="text/javascript"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>

<div class="container">
<div class="jumbotron">
<h1>Opus</h1> 

<p>Retype your password {{user.name}}. </p> 

<div class="row">
<div class="col-md-5">
<form action="{% url 'site_app:redefine-password' user.id token %}" method="post">
{% csrf_token %}
{% bootstrap_field form.password  size='md' %}
{% bootstrap_field form.retype  size='md' %}

{% buttons submit='Send' layout='inline' %}{% endbuttons %}
{% bootstrap_form_errors form type='non_fields' %}

</form>

</div>
</div>
</div>
</div>


</body>
</html>

site_app/templates/site_app/signup.html
{% load bootstrap3 %}
{% load i18n %}

<html lang="en">
<head>
<meta charset="utf-8" />
<title>Opus</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="/static/jquery-ui.js"> </script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="/static/input-extensions.js"> </script>

<link rel="apple-touch-icon" sizes="180x180" href="/static/icons/apple-touch-icon.png">
<link rel="icon" type="image/png" href="/static/icons/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="/static/icons/favicon-16x16.png" sizes="16x16">
<link rel="manifest" href="/static/icons/manifest.json">
<link rel="mask-icon" href="/static/icons/safari-pinned-tab.svg" color="#5bbad5">
<link rel="shortcut icon" href="/static/icons/favicon.ico">
<meta name="apple-mobile-web-app-title" content="Opus">
<meta name="application-name" content="opus">
<meta name="msapplication-config" content="/static/icons/browserconfig.xml">
<meta name="theme-color" content="#ffffff">
</head>

<body>
<div class="container" >
  <div class="jumbotron">
    <h1 >Opus <small> (Sign up) </small></h1> 


<form id="form-user-data" method="post" action="{% url 'site_app:signup' %}" enctype="multipart/form-data">
{% csrf_token %}

{% bootstrap_field form.name  size='md' %}
{% bootstrap_field form.email  size='md' %}
{% bootstrap_field form.password  size='md' %}
{% bootstrap_field form.retype  size='md' %}

{% bootstrap_field form.avatar  size='md' %}
{{ form.captcha  }}

{% bootstrap_form_errors form type='non_fields' %}

{% buttons submit='Sign up' layout='inline' %}{% endbuttons %}

</form>

</div>
</div>

</body>

site_app/templates/site_app/upgrade.html
{% load bootstrap3 %}
{% load i18n %}

<div class="modal-header">
<button type="button" class="close" data-dismiss="modal">&times;</button>
<h4> <span class="glyphicon glyphicon-credit-card"></span> Payment Settings </h4>

</div>
<div class="modal-body">

<h4> Current state </h4>
<p>Expiration: {{ me.expiration }}</p>

<h4> Current state </h4>
<p>Expiration: {{ me.expiration }}<br>
Max users: {{ me.max_users }}</p>

<h4> Purchases </h4>
<div class="pre-scrollable">
{% for ind in items %}
<p> 
Max Users: {{ind.period.max_users}} 
<br>
Total: {{ind.period.total}} {{CURRENCY_CODE}}
<br>
Expiration: {{ind.period.expiration}}
<br>
Type: {% if ind.period.paid %} Plan Paid {% else %}  Plan Free {% endif %}
<br>
Date: {{ind.period.created}}
<br>

{% if ind.payment_process.success %}
<small class="text-success"> Paid successfully! </small>
{% endif %}
<p>
{% empty %}
<p> No items. </p>
{% endfor %}

</div>

</div>

<div class="modal-footer">

<div class="text-center">
 <a class="s-modal" data-show="{% url 'site_app:paypal-manual-payment' %}" href="#"> Paypal </a> 
<a class="s-modal" data-show="{% url 'site_app:custom-payment' %}" href="#"> Custom </a> 

{% if me.paid %}
<a class="s-modal" data-show="{% url 'site_app:confirm-downgrade-free' %}" href="#"> Downgrade Free </a> 
{% endif %}
</div>

</div>